[package]
name = "snarkvm-algorithms"
version = "0.0.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Algorithms for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[[example]]
name = "gm17"
path = "examples/snark/gm17.rs"

[dependencies.snarkvm-errors]
path = "../errors"
version = "0.0.2"
default-features = false

[dependencies.snarkvm-models]
path = "../models"
version = "0.0.2"
default-features = false

[dependencies.snarkvm-profiler]
path = "../profiler"
version = "0.0.2"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.0.2"
default-features = false

[dependencies.blake2]
version = "0.8.1"

[dependencies.derivative]
version = "2"

[dependencies.digest]
version = "0.8.1"

[dependencies.itertools]
version = "0.9.0"

[dependencies.rand]
version = "0.7"

[dependencies.rand_chacha]
version = "0.3.0"

[dependencies.rayon]
version = "1"

[dependencies.sha2]
version = "0.9"

[dependencies.smallvec]
version = "1.4"

[dev-dependencies.snarkvm-curves]
path = "../curves"

[dev-dependencies.criterion]
version = "0.3.3"

[dev-dependencies.csv]
version = "1"

[dev-dependencies.rand_xorshift]
version = "0.2"

[features]
default = [
  "pedersen-parallel",
  "snarkvm-errors/default",
  "snarkvm-models/default",
  "snarkvm-utilities/default"
]
pedersen-parallel = [ ]
print-trace = [ "snarkvm-profiler/print-trace" ]
